######################################################################
# Automatically generated by qmake (3.1) Mon Apr 6 23:34:23 2026
######################################################################

TEMPLATE = app
TARGET = calcul_itineraire
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += IHM/LoginDialog.h \
           IHM/MainView.h \
           IHM/MainWindow.h \
           IHM/MiniView.h \
           models/BDD.h \
           models/Carte.h \
           models/Contour.h \
           models/Graphe.h \
           models/Point.h \
           models/Route.h \
           models/SceneCarte.h \
           models/Ville.h \
           models/Waypoint.h
SOURCES += main.cpp \
           IHM/LoginDialog.cpp \
           IHM/MainWindow.cpp \
           models/BDD.cpp \
           models/Graphe.cpp \
           models/SceneCarte.cpp
QT += widgets
